### ISSUE TITLE
Dual_BPF_Schematic.pdf

### ISSUE THREAD

**Issue by DH1KLM** [F6ITU/Dual_BPF#1]
Hi Marc,

schematic Dual_BPF_Schematic.pdf is identical to AlexV2_schematic.pdf.

Or have I misunderstood something?

**Comment by F6ITU** [comment]
Oh, so sorry, Sigi

By default, Kicad keeps the same path when « printing to pdf » the schematic… and when I updated the repository, I didn’t check the containt.

Github has been fixed

Thnks again
Marc

Ps : Kicad version of Aries has been finished yesterday. I will modify some small details, but so far, it’s probably a « real clone » of LA2NI’s board
https://github.com/F6ITU/K_Aries

… and I’m beginning the kicad for Munin 400. I’ll try to build the « dual bpf » next week to measure the « real life » filter



De : Sigi ***@***.***>
Envoyé : jeudi 11 mai 2023 18:54
À : F6ITU/Dual_BPF ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [F6ITU/Dual_BPF] Dual_BPF_Schematic.pdf (Issue #1)


Hi Marc,

schematic Dual_BPF_Schematic.pdf is identical to AlexV2_schematic.pdf.

Or have I misunderstood something?

**Comment by DH1KLM** [comment]
I'm already curious about the Dual BPF.

**Comment by F6ITU** [comment]
kicad version of the relay board almost done (still some silkmask cleaning, adding iBom and other small stuff to finish)https://github.com/F6ITU/K_Relay_Board  and I will be free to build and test the BPF

**Comment by F6ITU** [comment]
Hi Sigi

These are the « raw » real filter measurements.
I didn’t solder the LNA MMIC, that’s why you cannot see the 6m band (but if you absolutely need them, I will build a specific test setup asap)

So far, results are  identical compared with the bpf filter used in the Anan 7000DLE and 8000DLE. No more, no less.

The upper slope of each filter  is not significant, as in the « real life », you should add the Q of the LPF « tx » filter which is always in series with the RX bpf

From a practical point of view, results cannot be compared with the « old fashioned » HPF + BPF eliptical filters of the former Alexiares frontend. This bpf filter is considerably easier to build and the crossover frequencies are perfectly choosen for people involved in ham radio
But for people listening for wide spread spectrum transmissions, frequencies located in the « crossover zone », wishing to have a real « high end » filter with a rejection of more than 80 -90 dB, and looking for a variable bandpass filter using combination of different hpf and lpf filters, nothing can replace the « alex old style ».

In other words, I think my next Angelia and Anvelina boards will  use the old hpf for RX1 path and one SMD bpf for RX2 path (as the Alex protocol cannot combine more than one lpf  during RX). This way, I’ll have a «more spurious free » RX2 path with grounding of the second adc when transmiting, and a high performance RX HPF+BPF filter in the RX1 path. The new Alexandrie V2 board can handle this kind of configuration.

When Apache labs decided to abandon the hpf-bpf architecture and replace it with the SMD based bpf, it  was for 2 reasons :

  *   It cost a lot less than the hpf with less tuning hassle
  *   Very few ham where able to understand this architecture and were using Alex configuration by default, as they only whist to use an OpenHPSDR architecture like any other analog transceiver.
So, why shouldn’t they choose the « easy way » ?

I definitely should test this bpf filters combination on my Red Pitaya rigs…. They are the perfect candidates for this kind of frontend

Have a nice day, Sigi
73’
Marc f6itu

De : Sigi ***@***.***>
Envoyé : dimanche 14 mai 2023 12:05
À : F6ITU/Dual_BPF ***@***.***>
Cc : Marc OLANIE ***@***.***>; Comment ***@***.***>
Objet : Re: [F6ITU/Dual_BPF] Dual_BPF_Schematic.pdf (Issue #1)


I'm already curious about the Dual BPF.
